### PR TITLE
Update to Eigen 3.2.5

### PR DESCRIPTION
**Pull request by yixuan**
Hello All,
This PR updates RcppEigen to Eigen 3.2.5, and all dependent packages have passed the check.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You're amazing. This looks like excellent work.  

Will take a closer look tomorrow, and probably roll it up then.

**Comment by yixuan** [comment]
Thanks Dirk.
Now there is one more complexity.
In fact the `OpenMx` package will have compiler error when linked to the original Eigen 3.2.5 source, and hence I added a tiny patch to Eigen contained in `RcppEigen` (https://github.com/yixuan/RcppEigen/commit/42e183ec3794f9fa04c9e16098d98ff2d7fbbd39).
However, later I found that this is not the fault of Eigen, but rather a misuse by the `OpenMx` package.
The reason is simple: somewhere in the code Eigen will cast a pointer to an integer type, which is defined to be `std::ptrdiff_t` (equivalent to `long int`) by default. However, the `OpenMx` package pre-defined this type to be `int`, so when we reach the code where pointer is cast to integer, the compiler will give an error that `const double *` cannot be cast to `int`.
Due to this fact we have two solutions:
1. Keep the patch I added to RcppEigen, but this obeys "a clean import" principle.
2. Contact the author of `OpenMx` to avoid the misuse (just one line change), and we wait for the update of `OpenMx` before we raise `RcppEigen` up.

Which approach would you prefer?

**Comment by eddelbuettel** [comment]
I think I prefer 2.

**Comment by yixuan** [comment]
Thanks. I think you could simply revert the most recent commit and later I'll send an email to the OpenMx group.

**Comment by eddelbuettel** [comment]
Yes, I agree on both counts. I'll have to a do a bit of micro-fixing for all the recent R-devel changes to R C MD check but should be ready later. We should email the OpenMx folks today.

**Pull request merged**
