### PR TITLE
Update to Eigen 3.2.8 and fix UBSAN error

### PR DESCRIPTION
**Pull request by yixuan**
This PR imports Eigen 3.2.8 and applies the upstream patch to solve UBSAN errors. All dependent packages except `gpuR` have passed the check.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Lovely work, as usual -- really appreciate it.  

May run another rev.dep check for good measure and ship it then.

**Comment by yixuan** [comment]
Sounds good! Hope this version solves the problem.

**Comment by eddelbuettel** [comment]
Hope so too; it is in the queue at CRAN now.  Take a look at [this](https://github.com/RcppCore/RcppEigen/commit/8fb216a4d95a53016b90d9dd1d3e5845d1e4d508) which was way overdue ...

**Comment by yixuan** [comment]
Wow, just noticed that. Thank you so much!

**Comment by yixuan** [comment]
Hmm, seems another one:http://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/RcppEigen/tests/doRUnit.Rout.
Let me see if we have any quick fix.

**Comment by eddelbuettel** [comment]
Ugggh.  Thanks for looking into it!

**Comment by yixuan** [comment]
This should not affect dependent packages much, though. It appears in a sparse Cholesky decomposition, which is not so frequently used in reverse dependencies.

**Comment by eddelbuettel** [comment]
OTOH among the 50-ish packages using RcppEigen, quite a few do so because of sparse matrix algebra which RcppArmadillo is/was lacking...

**Comment by yixuan** [comment]
I've submitted a bug: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1172.
Sorry about that. :-\

**Comment by eddelbuettel** [comment]
:+1: and no worries.  We squash them one by one.  

When you hear back we can fold that into a 0.3.2.8.1 release.

**Pull request merged**
