### PR TITLE
update Eigen version to 3.3.1

### PR DESCRIPTION
**Pull request by ChingChuan-Chen**
This PR imports Eigen 3.3.1 to RcppEigen.

Eigen 3.3.2 has been released two days ago, it is the time to update Eigen to 3.3.X.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thank you.  Are you aware that a few of our files from 3.2.9.* had local patches?  Did you preserve those?

**Comment by ChingChuan-Chen** [comment]
Sorry, I don't know that, where can I find the record for those local patches?
I don't find the commit log for those.

**Comment by eddelbuettel** [comment]
Let's close this PR.  Open an issue ticket and we walk you through.

The `#define` is wrong too.  Help is welcome, but don't stomp in like this.  If it were this easy we had loing done it.

**Comment by ChingChuan-Chen** [comment]
Sorry for that, 

I only take care of [this](https://github.com/RcppCore/RcppEigen/blob/master/inst/include/Eigen/CholmodSupport#L9) and [this](https://github.com/RcppCore/RcppEigen/blob/master/inst/include/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h#L181-L183) is not awared.

**Comment by yixuan** [comment]
Hi ChingChuan,
Thanks for preparing the update. As Dirk said, we had a few manual patches, and most importantly, our major concern is the compatibility with dependent packages, so before updating the Eigen version in RcppEigen, we need to run a reverse dependence check on those packages.

In fact we have already started the update process, but due to a few regressions in Eigen 3.3 we had to delay it. Since 3.3.2 is out, I think it is time to restart. If possible I'll fork your patch later and then test against the dependent packages.

**Pull request closed without merging**
