### PR TITLE
Eigen 3.4.0

### PR DESCRIPTION
**Pull request by yixuan**
This PR should have solved the issue mentioned in https://github.com/RcppCore/RcppEigen/issues/101.

The problem was that in Eigen 3.4.0, `Eigen/src/CholmodSupport/CholmodSupport.h` introduced a series of `cholmod_l_*` functions intended for the `long` integer type, which were not defined in `RcppEigenCholmod.h`. The fix is to remove the definitions of those functions, as they are not used by RcppEigen.

Note that I have only tested the building of RcppEigen itself and that of my own RSpectra package. I expect that there may be some issues for other packages depending on RcppEigen. We still need @eddelbuettel to schedule a (large-scale) automated test for the huge number of dependent packages.

### CODE REVIEW

**Comment by waynelapierre** [comment]
Any updates on this PR?

**Comment by eddelbuettel** [comment]
Please see https://github.com/RcppCore/RcppEigen/issues/103 and help as you can.

**Comment by eddelbuettel** [comment]
I think I got the merge conflicts sorted the right way --- but it might benefit from another glance or two by @jaganmn at the merge commit 4db13cb44439c5f296a3310ae16ce8067494b1af .

**Comment by andrjohns** [comment]
@eddelbuettel I re-ran the revdep checks with this branch and `lme4` and `OpenMx` both pass now (thanks for sorting that so quickly @jaganmn!).

Down to 8 packages on CRAN that break, with three having already merged patches: https://github.com/RcppCore/RcppEigen/issues/103#issuecomment-1894705892

**Comment by jaganmn** [comment]
I left [one comment](https://github.com/RcppCore/RcppEigen/commit/4db13cb44439c5f296a3310ae16ce8067494b1af#r137320746) on Dirk's merge commit, but apart from that it seems OK.

**Comment by eddelbuettel** [comment]
Just replied to @jaganmn there and in short I was just trying to move the PR over a hump of a merge conflict. I may have done that in haste.

**Comment by eddelbuettel** [comment]
Lovely stuff. Thank you all -- will turn on a rev.dep run here too.

**Comment by eddelbuettel** [comment]
> Thanks, on its way to CRAN.

Yay!

Thoughts on how to merge as per my previous comment?

**Comment by yixuan** [comment]
This is fantastic!!

I really have no preference on the merging strategy here. But if I have to make a choice, I may vote for the cleaner way. To be honest, I was always puzzled by git histories with multiple sources of changes. 🤣

Other thoughts?

**Comment by eddelbuettel** [comment]
Hey -- good to hear from you.   I am really torn.  I like 'linear' -- at work we enforce it via 'squash merge':  each PR is a squash.

image

I don't mind standard PR with (usually) just one departure:

image

I am less of a fan where it gets 'wild'

image

Because yours started so long ago we'd have a really long parallel history.  But then again we a) have never squashed and b) it's nice if your work is reflected as is.

So kinda leaning towards normal 'noisy' merge.  What do you think?

[ But most importantly: it does not really matter.  Code quality matters, clean tests, good ci.  This is mostly cosmetic.  It matters really only a little bit. ]

**Comment by yixuan** [comment]
Hi Dirk, if the consideration is on reflecting "my work" then I really do not mind squashing it. The changes mostly come from upstream Eigen, and I would not take that much credit. 😄

**Comment by eddelbuettel** [comment]
Ok -- squash it is then!  (I switched in Rcpp too.  It is cleaner.  Will take a while til we have a 'page full' though <grin> )

**Pull request merged**
