### PR TITLE
Update to Eigen 3.2.7

### PR DESCRIPTION
**Pull request by yixuan**
This PR imports Eigen 3.2.7. All dependent packages except `gpuR` (my machine lacks the required library) have passed the check.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You rock. I also exclude gpuR from regular Rcpp(Eigen) tests.

Much appreciated, as always.

**Comment by yixuan** [comment]
You are welcome. It didn't take much time on each update. Just need to run some routine tests (and be patient waiting for the results).

**Comment by eddelbuettel** [comment]
I just got an error with R-devel :-/

```
RcppEigen unit testing - 25 test functions, 1 error, 0 failures
ERROR in test.sparseCholesky.R: Error in as.vector(x@x, mode) : 
  argument "mode" is missing, with no default
```

I'll take a look.

**Comment by yixuan** [comment]
OK. Seems to be in the R side. I'll take a look at the unit tests later.

**Comment by eddelbuettel** [comment]
Could be newer R-devel here with an outdated Matrix package. Error makes no sense. Comes from the R part of

```r
    checkEquals(rr[[1]], as.vector(solve(crossprod(KNex[[1]]),
                                         crossprod(KNex[[1]], KNex[[2]]))),
                                       "Cholmod solution")
```

**Comment by eddelbuettel** [comment]
Adding a trailing  `, mode="numeric")`  makes it pass in R-devel, and does not seem to do harm in R-release it seems.  Testing again now, will commit in moment if it pans out.

Seems like a bug in the R-devel version I use...

**Comment by yixuan** [comment]
Great. When I find time I may update and clean other unit tests as well.

**Comment by eddelbuettel** [comment]
Committed as https://github.com/RcppCore/RcppEigen/commit/ea2de6730fc61b6db04e57a13f3ee3a62cbda0a8
Everything looks fine.  I'll run a rev.dep check as well overnight and will likely submit tomorrow.

**Comment by eddelbuettel** [comment]
Maybe not a bug.  Looks like `as.vector(sqrt(1:10))` still works.  But when ints are submitted we now need `mode="numeric"`.  Might be on purpose :)

**Comment by eddelbuettel** [comment]
Ok, it _was_ a regression in r-devel. I updated, and the issue is gone.  So my commit wasn't needed (but won;t hurt).

I had a mild panic because several of the rev.dep packages fell for the same 'error'.  It is a non-backwards compatible change, so it had to be reverted.

**Comment by yixuan** [comment]
Good catch!

**Pull request merged**
