### PR TITLE
Update to Eigen 3.3.9 (closes #91)

### LINKED ISSUE #91: Eigen 3.3.8 release candidate
Just an fyi there's a release candidate for [Eigen 3.3.8](https://gitlab.com/libeigen/eigen/-/tags/3.3.8-rc1) available

[Change Log](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.8-rc1)

### PR DESCRIPTION
**Pull request by eddelbuettel**
So procrastination does pay off after all.  By "waiting" and being unware of the 3.3.8 all this time it so happens that 3.3.9 came out yesterday.

Carrying the changes over was fairly painless, and I snuck in a few of the regular updates.  I will put this in the [Rcpp drat]() repo in a few minutes so that you can get a tarball from there but before I upload to CRAN (or even get to reverse dependency checks, currently running one for Rcpp which will eat up a few more hours) I would love for your guys at 'team stan' to test it. So flagging a few of you with review requests.  Hope that is ok.  @SteveBronder @bgoodri 

PS Done.  You can install it via `install.packages("RcppEigen", repos="https://rcppcore.github.io/drat")'` as usual.   And yes, compilation is still as noisy as always because that, for better or worse, is how CRAN rules.

### CODE REVIEW

**Comment by bgoodri** [comment]
I am getting a build error with rstan ( https://github.com/stan-dev/math/issues/2235 ) that seems to be due to changing the number of required number of template arguments in some traits-related thing. We'll try to fix it ASAP.

**Comment by eddelbuettel** [comment]
Thanks for checking so promptly!  I guess I would have run into this too by rev.dep-ing (when I get to it).  There is no rush, as you know I was following on 3.3.7 exactly overnight...  We'll do this the right way.

**Comment by yixuan** [comment]
This is super awesome, Dirk!

**Comment by eddelbuettel** [comment]
@yixuan I have no choice as you set such an example example so many times ;-)

**Comment by yixuan** [comment]
In fact I created a branch yesterday trying to update the new version, as I felt so guilty that I didn't have much time on this for the last few releases. And then I surprisingly found that you have finished everything in such a short time. 😂

**Comment by eddelbuettel** [comment]
Hi @bgoodri I think I ran into the same issue reverse-depends checking the new version -- a lot of `StanHeaders` clashing.

Let's see over the next few days if we can come up an upgrade path of updating `StanHeaders` first and then re-assessing what other changes a new `RcppEigen` may trigger.  

In the meantime, I may merge this PR because the package is ok _per se_ but just not ready to interact with the rest of CRAN.

**Comment by bgoodri** [comment]
@eddelbuettel Yes, I would anticipate that almost everything related to Stan on CRAN will fail to build because this change affects the numerical traits of custom-defined scalar types that we use in Stan for automatic differentiation (but non-Stan packages that just use `int`, `double`, etc. are probably not affected). It seems likely that StanHeaders will have to branch on `EIGEN_MINOR_VERSION` in order for Stan stuff to build with the current RcppEigen on CRAN and the future RcppEigen.

**Comment by eddelbuettel** [comment]
@bgoodri @stevebronder Any news about the `StanHeaders` change?  Keep me posted...

**Comment by bgoodri** [comment]
I think we're good but haven't run the CRAN checks yet (I'm braving the
airports today so won't be able to kick them off until tonight)

**Comment by eddelbuettel** [comment]
Thanks for the update. There is obviously no urgency, I just wanted to see where it's at.  

So we should be able to do a two-step: once updated, StanHeaders goes to CRAN, I resume my rev.dep tests which should look better ;-) and then hopefully RcppEigen 0.3.3.9.* at CRAN.

**Comment by SteveBronder** [comment]
Yes Rok just updated stan math to support 3.3.9 so should be hopefully be smooth(er) sailing. Thanks for updating this Dirk much appreciated!

**Comment by eddelbuettel** [comment]
I think I saw that in the (large) referenced commit.  

But I guess I'd need an updated StanHeaders package on CRAN so that the reverse dependencies checks get that update along with my RcppEigen 0.3.3.9.* check.  I presume I will see it via CRANberries but any timeline visibility over from your end about when/if it may ship to CRAN?

**Comment by bgoodri** [comment]
I started running the reverse dependency checks for StanHeaders yesterday. The new StanHeaders with the old RcppEigen seems to be OK. I will start the checks with the new StanHeaders and the new RcppEigen now.

**Comment by eddelbuettel** [comment]
Nice, thanks -- I could turn my instance on as well if you let me have the candidate tarball.  Is there a `drat` repo anywhere?

In other news, and because the fun never stops, I am right now preparing BH 1.75.0-0 based on yesterday's Boost 1.75.0.

**Comment by bgoodri** [comment]
Here is a tarball: [StanHeaders_2.21.0-7.tar.gz](https://github.com/RcppCore/RcppEigen/files/5683396/StanHeaders_2.21.0-7.tar.gz). So
```
install.packages("https://github.com/RcppCore/RcppEigen/files/5683396/StanHeaders_2.21.0-7.tar.gz", repos = NULL)
```
should work.

**Comment by eddelbuettel** [comment]
Nice, thanks! Currently noodling over BH 1.75.0-0 which will take a moment but should be able to turn this on later today.

**Comment by eddelbuettel** [comment]
Started a reverse depends run, will know full results tomorrow but _so far, so good_:  the first handful of (early in the full set) failures for the last round now pass -- so looks like this is doing what it was supposed to do :+1:

**Comment by eddelbuettel** [comment]
'All clear' from my end, see the (now committed) [result summary](https://github.com/RcppCore/rcpp-logs/blob/0711e3365dbcb5f6a23dda75481e2cb5324f347c/results/rcppeigen/RcppEigen-QuickSummary-20201212.txt) -- no compilation issues or test regressions over 270 packages.

So once `StanHeaders` is on CRAN, `RcppEigen` can follow.  Thanks so much to @rok-cesnovar for the prompt update.

**Comment by rok-cesnovar** [comment]
Glad to help. Thank you for maintaining this great package!

**Comment by eddelbuettel** [comment]
How are things looking with respect to a CRAN upload for `StanHeaders`?  

@bgoodri @SteveBronder @rok-cesnovar : any insight?  This _is_ the critical path for `RcppEigen` which I updated thanks to your nudging but cannot actually upload unless you update first.

**Comment by rok-cesnovar** [comment]
@bgoodri is handling CRAN matters, I think he was traveling last week, not sure.

**Comment by bgoodri** [comment]
I am going to try to upload it to CRAN this afternoon. I ran it with the
rstan reverse dependencies because there are 50 or so more packages that
are depending on the libraries through rstan, but they seem to be fine too.

**Comment by eddelbuettel** [comment]
That would be great.  As your results are clean too (apart from the usual directory size) it may auto-process after reverse depends checks gving `RcppEigen` a chance to follow suit and sneak in before the gate closes for two weeks.

**Comment by bgoodri** [comment]
The new StanHeaders made it to CRAN, so you should be good to upload
RcppEigen now.

**Comment by eddelbuettel** [comment]
New RcppEigen prepared, submitted, pretested, and fell victim to one false positive as `hsstan` has a NOTE on "GNU make" which is not us.  So should be on CRAN "soon".

**Pull request merged**
