### PR TITLE
Eigen 3.3.4

### LINKED ISSUE #48: Update Frequency?
I was wondering how often the 'newest' Eigen headers are ported in to this package?  As what usually happens, I am dealing with GPU related problems and I noticed one pull request on the [eigen bitbucket](https://bitbucket.org/eigen/eigen/pull-requests/311/eigen-compilation-with-nvcc/activity) website that addressed the problem (quite minor in this case).  I saw that it was merged back in May 2017 but the change isn't reflected in RcppEigen.  Was a new 'official' release not provided by the Eigen authors perhaps?  

I don't mean to push, as again this issue is quite minor in this instance.  I am only curious how/when you decide to update the headers herein from the Eigen source.

### PR DESCRIPTION
**Pull request by yixuan**
This PR updates the included Eigen to 3.3.4, and also applies some upstream patches used to fix #48 .

@eddelbuettel I haven't got the time to run a reverse-dependence check for this PR. Could you run it on the automated server and show me the report? I'd like to look into the cause of potential failures as usual. Thanks!

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Awesome.  I'll start a rev.dep run in a moment.

**Comment by eddelbuettel** [comment]
Looks good. I ran one, and saw no compilation issue.  There were a few tests failing where packages had Suggests: yet required the package present---I will skip those packages in a second run.

**Comment by eddelbuettel** [comment]
One test failure (Cyclops) which gets the same failure under RcppEigen 0.3.3.3.1, so no regression.

**Comment by eddelbuettel** [comment]
Hu @yixuan should we care about this?  Logs from r-devel on 0.3.3.4.0:
https://win-builder.r-project.org/bWF1JR2EGjK6/00check.log

I guess we may be able to argue the `long long` away ("them, not us").  Should we deal with the pragma issue?

**Comment by yixuan** [comment]
My bad. I accidentally overwrote this commit: https://github.com/RcppCore/RcppEigen/commit/a56f72dc1cf42aaf8c9f4d5beb466ab46fa89f1e. Could you make a quick fix? I think I should report it to Eigen so that next time we do not need to make a manual patch.

**Comment by eddelbuettel** [comment]
I just reapplied https://github.com/RcppCore/RcppEigen/commit/a56f72dc1cf42aaf8c9f4d5beb466ab46fa89f1e as d934b12c12886fece65b7bc57030e61c735566a3 but am a little worried about the remainder of the build log:

```
* checking pragmas in C/C++ headers and code ... WARNING
File which contains pragma(s) suppressing important diagnostics:
  'inst/include/Eigen/src/Core/arch/SSE/Complex.h'
File which contains pragma(s) suppressing diagnostics:
  'inst/include/Eigen/src/Core/util/DisableStupidWarnings.h'
* checking compiled code ... OK
```

We may have to comment the pragmas out.  :-/

**Comment by eddelbuettel** [comment]
Done in 6247fd632ad6ee78daffa0acff9ff1af8d7aaaa5 and I will run another set of reverse depends tests later; easy enough now thanks to [prrd](http://dirk.eddelbuettel.com/code/prrd.html).

**Comment by yixuan** [comment]
Thanks for the help! I'll document them in my notes and remember to apply these manual patches next time. `prrd` looks great!

**Comment by eddelbuettel** [comment]
Shall we, just for our reference, create a recursive diff of "our" Eigen 3.3.4 versus upstream?  We could stick it into a top-leve directory excluded via `.Rbuildignore`.

**Comment by yixuan** [comment]
Great. Will do that later today.

**Comment by eddelbuettel** [comment]
BTW suppressing the `#pragma` makes even `R CMD INSTALL RcppEigen` extremely "noisy" :-/

**Comment by yixuan** [comment]
Yeah, I see that... Even the 0.3.3.3.1 package now has warnings under R-devel: https://cran.r-project.org/web/checks/check_results_RcppEigen.html.

**Comment by eddelbuettel** [comment]
Yes, those checks are new-ish. (I run one robot diff'ing CRAN Policy and tweeting / committing changes.  I think this may have been added last November or December.)

**Comment by eddelbuettel** [comment]
I cherry-picked your commit with the diff to Eigen 3.3.4.  Minor change to directory layout but nothing substantial.  Thanks for setting that up.

**Comment by yixuan** [comment]
Thank you Dirk!

**Comment by cdeterman** [comment]
@yixuan if I may ask how do you decide what to include or how you figure out what is in each version?  I saw this previous pull request on the Eigen bitbucket [here](https://bitbucket.org/eigen/eigen/pull-requests/327/cuda-90-support/diff) that contains additional changes (among a few additional small changes also in the github mirror) I need for some of my work.  I have made the updates in my own [fork](https://github.com/cdeterman/RcppEigen) of RcppEigen but I don't know how you want to manage pull requests.

**Comment by yixuan** [comment]
As I have explained in #50 , `RcppEigen` now tracks the stable [`3.3`](https://bitbucket.org/eigen/eigen/branch/3.3) branch of Eigen. So if you need some features that are in the [`default`](https://bitbucket.org/eigen/eigen/branch/default) branch of Eigen, you can report to the developers to back-port them to the `3.3` branch.

**Comment by cdeterman** [comment]
@yixuan Do you know how else I can get in touch with the Eigen developers?  I tried subscribing to the [mailing list](http://eigen.tuxfamily.org/index.php?title=Main_Page#Mailing_list) but I have yet to hear anything back over the last two weeks.  Wasn't sure if there was another way to reach out.

**Comment by yixuan** [comment]
@cdeterman Gael has a public email <gael.guennebaud@gmail.com>, but from the commit log of Eigen I guess he was tied up by something else and didn't get the time for Eigen development at this moment.

**Pull request merged**
