### PR TITLE
Another UBSAN patch for Eigen 3.2.8

### PR DESCRIPTION
**Pull request by yixuan**
Hi @eddelbuettel ,
I had this patch from Eigen: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1172.
However I was unable to check it on `RcppEigen` and dependent packages, since it seems that I need to recompile everything in my local machine. Do you have any environment to test it?

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I just run a big loop, installing to subdirectory below /tmp -- see [the simple script here](https://github.com/RcppCore/rcpp-logs/blob/master/scripts/runRcppEigenDepends.r).

Will turn that on in a moment.  Big thanks, as always, for "taking care of business".

**Comment by eddelbuettel** [comment]
Sorry, got distracted yesterday.   Reverse-Depends check passed just fine, I will wrap this up later this evening and send it out.

Is it your understanding that this change is now in upstream as well, or do we need a reminder to re-apply it next time?

**Comment by yixuan** [comment]
Thanks for the careful check! It will appear in the next release.

**Comment by eddelbuettel** [comment]
Great. One less thing for us to worry about :)

**Pull request merged**
