### PR TITLE
Correct check for vectorization capabilities

### PR DESCRIPTION
**Pull request by dselivanov**
This fixes a minor issue with check for vectorization capabilities.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I am sorry but what is the problem this fixes?  I see

```r
R> RcppEigen:::Eigen_SSE()
[1] TRUE
R> 
```

**Comment by dselivanov** [comment]
But it doesn't show set of instructions supported by machine. Mb it is redundant... But for me it seems useful.

**Comment by eddelbuettel** [comment]
I guess it is suboptimal as we otherwise see

```r
R> Rcpp::cppFunction("void foo() { Rcpp::Rcout << Eigen::SimdInstructionSetsInUse() << std::endl; }", depends="RcppEigen")
R> foo()
SSE, SSE2
R> 
```

but 

- changing an existing interface is distasteful
- why not add a new function which splits up that character string and returns the components as in `c("SSE", "SSE2")`

Now, do we actually know if anybody uses this at all?   ;-)

**Comment by eddelbuettel** [comment]
Also, do we know if there are any CPUs not using SSE?  Paging @MattPD ...

**Comment by dselivanov** [comment]
Didn't think it is used by somebody in "production" code, since it is not part of public API. But I agree, it is better to write new function. Will it be useful for package? (For me it was just curiosity).

**Comment by MattPD** [comment]
@eddelbuettel Do we only care about x86 CPUs?
If so, nowadays SSE2 is supported by the vast majority of these--and enabled by default by GCC as of x86-64. 

For reference: "[SSE instruction set] is supported by Pentium III and newer chips, and in the AMD line by Athlon-4, Athlon XP and Athlon MP chips. The earlier version of the SSE instruction set supports only single-precision arithmetic, thus the double and extended-precision arithmetic are still done using 387. A later version, present only in Pentium 4 and AMD x86-64 chips, supports double-precision arithmetic too. "
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options

As for not-only-x86, here's what Eigen supports:
https://bitbucket.org/eigen/eigen/src/54f36f9deaad8ec730ecdfee39c50aad32cfc4d1/Eigen/Core?at=default&fileviewer=file-view-default#Core-267

**Comment by eddelbuettel** [comment]
Yep, thanks, that's what I thought.  The whole thing is a non-issue and distraction.  I think we can just close this.

**Comment by dselivanov** [comment]
okay

**Comment by eddelbuettel** [comment]
Thanks. It was a valid point in the narrow sense, in the larger sense the function is irrelevant and could just return `TRUE` unconditionally and we might not notice   ...

**Pull request closed without merging**
